fio = input()
fio_apart = fio.strip()
words = fio_apart.split()
initials = "".join([word[0].upper() for word in words])
print(f"Инициалы: {initials}")
fio_full = fio_apart.replace(" ", "")
print(f"Длина (символов): {len(fio_full)+2}")
